/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import g2ejercicio04.Categoria;
import g2ejercicio04.Producto;
import java.util.TreeSet;

/**
 *
 * @author Alesio
 */
public class MenuGeneral extends javax.swing.JFrame {

    public static TreeSet<Producto> listaProductos = new TreeSet<>();

    /**
     * Creates new form MenuGeneral
     */
    public MenuGeneral() {
        initComponents();
        this.setLocationRelativeTo(null); //para que la ventana salga en el centro de la pantalla
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmenuAProductos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmenuCRubro = new javax.swing.JMenuItem();
        jmenuCNombre = new javax.swing.JMenuItem();
        jmenuCPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");

        jmenuAProductos.setText("Productos");
        jMenu1.add(jmenuAProductos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jmenuCRubro.setText("Por Rubro");
        jmenuCRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCRubroActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuCRubro);

        jmenuCNombre.setText("Por Nombre");
        jmenuCNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCNombreActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuCNombre);

        jmenuCPrecio.setText("Por Precio");
        jmenuCPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuCPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(jmenuCPrecio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmenuCRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCRubroActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConsultasXRubro cxr = new ConsultasXRubro();
        cxr.setVisible(true);
        escritorio.add(cxr);
        escritorio.moveToFront(cxr);
    }//GEN-LAST:event_jmenuCRubroActionPerformed

    private void jmenuCNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCNombreActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ConsultasXNombre cxn = new ConsultasXNombre();
        cxn.setVisible(true);
        escritorio.add(cxn);
        escritorio.moveToFront(cxn);
    }//GEN-LAST:event_jmenuCNombreActionPerformed

    private void jmenuCPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuCPrecioActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        ConsultasXPrecio cxp = new ConsultasXPrecio();
        cxp.setVisible(true);
        escritorio.add(cxp);
        escritorio.moveToFront(cxp);
    }//GEN-LAST:event_jmenuCPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmenuAProductos;
    private javax.swing.JMenuItem jmenuCNombre;
    private javax.swing.JMenuItem jmenuCPrecio;
    private javax.swing.JMenuItem jmenuCRubro;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos() {
        listaProductos.add(new Producto(10, "Azucar x 1kg", 180.5, 75, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(15, "Yerbar x 1kg", 250, 50, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(20, "Miel x 1kg", 355.33, 10, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(21, "e x 1kg", 355.33, 10, Categoria.LIMPIEZA));
    }
}
